export const importTexts = {
  selectFiles: "Seleccionar certificados PDF o Excel (.xlsx)",
  title: "Importar actas de molino",
  description: "Los certificados y libros Excel se procesan localmente.",
  submit: "Enviar archivos",
  uploading: "Enviando archivos…",
  empty: "No hay archivos seleccionados.",
  selected: (count: number) => `${count} archivo(s) seleccionado(s).`,
  received: "Procesamiento terminado. Los datos están disponibles en la cola de revisión.",
  queued: "Recibido para procesamiento",
  duplicate: "Archivo ya registrado",
  pendingReview: "Pendiente de revisión",
  processing: "Procesando archivos…",
  progress: (name: string) => `Procesamiento de ${name}`,
  retryTracking: "Reintentar consulta de progreso",
  jobStatus: {
    queued: "En cola",
    running: "Procesando PDF/OCR o Excel",
    succeeded: "Datos guardados",
    needs_review: "Datos guardados; requieren revisión",
    needs_ocr: "OCR no disponible; requiere atención",
    failed: "Procesamiento fallido",
    cancelled: "Procesamiento cancelado",
  },
  saving: "Guardando datos",
  trackingError: "No se pudo consultar el progreso",
  retryAttempt: (attempt: number) => `Reintento ${attempt}`,
} as const;
